apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodes-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-nodes-global
subjects:
- kind: ServiceAccount
  name: app
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: nodes-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: app
      containers:
      - name: app
        image: swr.ap-southeast-3.myhuaweicloud.com/core/app:v3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  annotations:
    kubernetes.io/elb.class: performance
    kubernetes.io/elb.autocreate:
      '{
        "type": "public",
        "bandwidth_name": "cce-bandwidth-app",
        "bandwidth_chargemode": "traffic",
        "bandwidth_size": 5,
        "bandwidth_sharetype": "PER",
        "eip_type": "5_bgp",
        "available_zone": [
          "ap-southeast-3a",
          "ap-southeast-3e"
        ],
        "l4_flavor_name": "L4_flavor.elb.s1.small"
      }'
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
#    kubernetes.io/elb.subnet-id: 69fc9f0a-e325-4d9b-b85d-c73ae9bc2ec6
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 0
      name: app-service
  type: LoadBalancer
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: app-ingress
#  annotations:
#    kubernetes.io/elb.class: performance
#    kubernetes.io/elb.port: '80'
#    kubernetes.io/elb.autocreate: 
#      '{
#          "type": "public",
#          "bandwidth_name": "cce-bandwidth-app",
#          "bandwidth_chargemode": "traffic",
#          "bandwidth_size": 5,
#          "bandwidth_sharetype": "PER",
#          "eip_type": "5_bgp",
#          "available_zone": [
#              "ap-southeast-3a",
#              "ap-southeast-3e"
#          ],
#          "l7_flavor_name": "L7_flavor.elb.s1.small"
#       }'
#spec:
#  rules: 
#  - host: ''
#    http: 
#      paths: 
#      - path: '/'
#        backend: 
#          service:
#            name: app-service
#            port: 
#              number: 80
#        property:
#          ingress.beta.kubernetes.io/url-match-mode: STARTS_WITH
#        pathType: ImplementationSpecific
#  ingressClassName: cce
---
apiVersion: v1
kind: Namespace
metadata:
  name: example-ns
