#cloud-config

package_upgrade: false
package_update: false
packages:
  - apt-transport-https
  - ca-certificates
  - curl
runcmd:
  - mkdir /root/app/
  - mkdir /root/.kube/
  - cd /root/
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  